spring.datasource.url: jdbc:h2:file:./camunda-h2-database

server:
  port: 8081

camunda.bpm.admin-user:
  id: demo
  password: demo
  firstName: Demo

#spring:
#  main:
#    allow-bean-definition-overriding: true
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: create-drop
#        show-sql: true
#        database: postgresql
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        open-in-view: true
#        generate-ddl: true
#
#  datasource:
#    driverClassName: org.postgresql.Driver
#
#    url: jdbc:postgresql://localhost:5432/camunda
#    username: root
#    password: root

